USE [master]
GO

/****** Object:  Database [ShoppingDB]    Script Date: 3/5/2024 3:13:07 PM ******/
CREATE DATABASE [ShoppingDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShoppingDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ShoppingDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShoppingDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ShoppingDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShoppingDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShoppingDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShoppingDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShoppingDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShoppingDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShoppingDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShoppingDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ShoppingDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShoppingDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShoppingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShoppingDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShoppingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShoppingDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShoppingDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShoppingDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShoppingDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ShoppingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShoppingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShoppingDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShoppingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShoppingDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShoppingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ShoppingDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShoppingDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ShoppingDB] SET  MULTI_USER 
GO

ALTER DATABASE [ShoppingDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShoppingDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShoppingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShoppingDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShoppingDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShoppingDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ShoppingDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ShoppingDB] SET  READ_WRITE 
GO


